

name: Create-Release

on:
  push:
    tags: v*


jobs:

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: setup Git Version
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Get Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Setup .Net SDK
        uses: actions/setup-dotnet@v2.0.0
        
      - name: Build project
        run: dotnet build -c "Release"
        
      - name: Pack project
        run: dotnet pack -c release /p:VersionPrefix=${{ steps.gitversion.outputs.nuGetVersionV2 }}
            
      - name: Publish Package
        run: dotnet nuget push **/*.nupkg --skip-duplicate -s "https://api.nuget.org/v3/index.json" -k  ${{secrets.NUGET_API_KEY}}

      - name: Publish to github
        uses: ncipollo/release-action@v1
        with:
          artifacts: "**/*.nupkg"
          generateReleaseNotes: true
          tag: v${{ steps.gitversion.outputs.nuGetVersionV2 }}
          artifactErrorsFailBuild: true 
      
